# Generated by Django 5.1.3 on 2024-11-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('Hours_of_support', models.IntegerField()),
                ('workers', models.IntegerField()),
            ],
        ),
    ]
