# Generated by Django 5.1.3 on 2024-11-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicApp', '0002_analytic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytic',
            old_name='Hours_of_support',
            new_name='HoursOfSupport',
        ),
    ]
